apiVersion: apps/v1
kind: Deployment
metadata:
  name: Listing-microservice
  labels:
    app: Listing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Listing
  template:
    metadata:
      labels:
        app: Listing
    spec:
      containers:
        - name: Listing
          image: microservicesproject:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080